export const t = {
  app: {
    name: "Al Sami Creation's",
    tagline: 'Hisaab Book',
  },
  auth: {
    login: 'Login',
    email: 'Email',
    password: 'Password',
    signingIn: 'Ruk jayein...',
    wrongDetails: 'Email ya password ghalat hai.',
    logout: 'Logout',
  },
  worker: {
    title: 'Karigar',
    add: 'Naya Karigar',
    name: 'Name',
    phone: 'Phone Number',
    search: 'Karigar dhoondein',
    cnic: 'CNIC',
    address: 'Address',
    notes: 'Notes',
    required: 'zaroori',
    empty: 'Abhi koi karigar shamil nahi kiya. Neeche + dabayein.',
    needNameAndPhone: 'Karigar ka naam aur phone number likhein.',
    save: 'Save',
    cancel: 'Cancel',
    saving: 'Ruk jayein...',
  },
  nav: {
    workers: 'Karigar',
    lots: 'Lot',
    report: 'Hisaab',
  },
  dress: {
    name: 'Dress Name',
    placeholder: 'Z 208',
    edit: 'Dress ki Tabdeeli',
    lotsOf: 'Is dress ke lot',
    minTotal: 'Itne dress pehle hi diye ja chuke hain.',
    recent: 'Pehle se mojood',
    needName: 'Dress ka naam likhein.',
    exists: 'Ye dress pehle se mojood hai. Isi mein lot add hoga.',
  },
  lot: {
    title: 'Lot',
    add: 'Naya Lot',
    number: 'Lot Number',
    search: 'Dress ya lot dhoondein',
    numberPlaceholder: '1',
    totalPieces: 'Total Dress',
    totalPlaceholder: '12',
    active: 'Active',
    closed: 'Closed',
    required: 'zaroori',
    needFields: 'Dress ka naam aur lot number likhein.',
    duplicate: 'Is dress ka ye lot number pehle se mojood hai.',
    empty: 'Koi lot nahi bana. Naya lot banayein.',
    noActive: 'Koi lot active nahi hai.',
    noClosed: 'Abhi tak koi lot close nahi hua.',
    save: 'Save',
    back: 'Back',
    total: 'Total',
    store: 'Store',
    issued: 'Diye',
    returned: 'Wapis',
    pending: 'Baqaya',
  },
  entry: {
    issue: 'Dress Diye',
    return: 'Wapis Mile',
    qty: 'Quantity',
    dress: 'dress',
    pickLot: 'Kaunsa Lot?',
    noLots: 'Koi lot chalu nahi hai. Pehle lot banayein.',
    nothingPending: 'Is karigar ke paas abhi koi dress nahi hai.',
    empty: 'Is karigar ko abhi tak kuch nahi diya.',
    pendingLabel: 'baqaya',
    summary: 'Diye',
    summaryReturned: 'Wapis',
    summaryPending: 'Baqaya',
    headerClear: 'Kuch baqaya nahi',
    note: 'Note',
    notePlaceholder: 'Koi baat likhni ho to',
    save: 'Save',
    back: 'Back',
    overReturn: 'Itne dress baqaya nahi hain. Pehle diye gaye dress add karein.',
  },
  chat: {
    diye: 'diye',
    wapis: 'wapis mile',
  },
  profile: {
    title: 'Karigar ki Tafseel',
    call: 'Call',
    whatsapp: 'WhatsApp',
    holding: 'Abhi Jo Dress Iske Paas Hain',
    nothing: 'Abhi koi dress nahi hai iske paas.',
    details: 'Tafseel',
    noValue: '—',
  },
  edit: {
    worker: 'Karigar ki Tabdeeli',
    dress: 'Dress ki Tabdeeli',
    changePhoto: 'Tasveer badalne ke liye tap karein',
    save: 'Save',
    back: 'Back',
    saved: 'Save ho gaya',
  },
  report: {
    title: 'Hisaab',
    today: 'Aaj',
    week1: '1 Hafta',
    week2: '2 Hafte',
    month1: '1 Mahina',
    custom: 'Apni Tareekh',
    from: 'Kis Tareekh Se',
    to: 'Kis Tareekh Tak',
    totalIssued: 'Total Diye',
    totalReturned: 'Total Wapis',
    byWorker: 'Karigar ke Hisaab Se',
    byDress: 'Dress ke Hisaab Se',
    empty: 'Is arse mein koi kaam nahi hua.',
    share: 'WhatsApp Par Bhejein',
  },
  users: {
    title: 'Users',
    add: 'Naya User',
    email: 'Email',
    password: 'Password',
    hint: 'Ye user sab kaam kar sakega — dress diye, wapis liye, karigar add. Sirf naye user nahi bana sakega.',
    defaultPass: 'alsami2026',
    saved: 'User ban gaya.',
    existing: 'Mojooda users',
    admin: 'Admin — naye user bana sakta hai',
    malik: 'User — sab kaam kar sakta hai',
    remove: 'Hatayein',
    removeConfirm: 'Is user ko hatana hai?',
    onlyAdmin: 'Sirf admin yahan aa sakta hai.',
  },
  common: {
    loading: 'Ruk jayein...',
    somethingWrong: 'Kuch masla ho gaya. Dobara koshish karein.',
  },
} as const