export const t = {
  app: {
    name: 'Karigar Book',
    tagline: 'Al-Sami Workshop',
  },
  auth: {
    login: 'Login',
    email: 'Email',
    password: 'Password',
    signingIn: 'Ruk jayein...',
    wrongDetails: 'Email ya password ghalat hai.',
    logout: 'Logout',
  },
    worker: {
    title: 'Karigar',
    add: 'Naya Karigar',
    name: 'Name',
    phone: 'Phone Number',
    cnic: 'CNIC',
    address: 'Address',
    notes: 'Notes',
    required: 'zaroori',
    empty: 'Abhi koi karigar shamil nahi kiya. Neeche + dabayein.',
    needNameAndPhone: 'Karigar ka naam aur phone number likhein.',
    save: 'Save',
    cancel: 'Cancel',
    saving: 'Ruk jayein...',
  },
  nav: {
    workers: 'Karigar',
    lots: 'Lot',
    report: 'Hisaab',
  },
  dress: {
    name: 'Dress Name',
    placeholder: 'Z 208',
    recent: 'Pehle se mojood',
    needName: 'Dress ka naam likhein.',
    exists: 'Ye dress pehle se mojood hai. Isi mein lot add hoga.',
  },
  lot: {
    title: 'Lot',
    add: 'Naya Lot',
    number: 'Lot Number',
    numberPlaceholder: '1',
    totalPieces: 'Total Dress',
    totalPlaceholder: '12',
    active: 'Active',
    closed: 'Closed',
    required: 'zaroori',
    needFields: 'Dress ka naam aur lot number likhein.',
    duplicate: 'Is dress ka ye lot number pehle se mojood hai.',
    empty: 'Koi lot nahi bana. Naya lot banayein.',
    noActive: 'Koi lot active nahi hai.',
    noClosed: 'Abhi tak koi lot close nahi hua.',
    save: 'Save',
    back: 'Back',
    total: 'Total',
    store: 'Store',
    issued: 'Diye',
    returned: 'Wapis',
    pending: 'Baqaya',
  },
  common: {
    loading: 'Ruk jayein...',
    somethingWrong: 'Kuch masla ho gaya. Dobara koshish karein.',
  },
} as const